name: Marvel Studios CI

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Selecionar Xcode estável
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Cache SwiftPM
        uses: actions/cache@v3
        with:
          path: ~/.swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}

      - name: Resolver dependências (SPM)
        run: xcodebuild \
          -resolvePackageDependencies \
          -project AplicativoMarvelStudios.xcodeproj

      - name: Build em simulador
        run: |
          xcodebuild \
            -project AplicativoMarvelStudios.xcodeproj \
            -scheme AplicativoMarvelStudios \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -quiet \
            build

      - name: Tudo certo!
        if: success()
        run: echo "🔥 Build finalizado com sucesso — pipeline rodando na main e develop!"
